#UNLOCK_STRING = b'|||CSL3B0mk@r|||'
#UNLOCK_STRING2 = b'|||||iOnTaP|||||'
#ITERATIONS = 100000
#HASH_METHOD = 'sha256'
#USERNAME_PADDING = 16
#
#SUCCESS = 'Success'
#RSA_ERROR = 'Error in RSA'
#AES_ERROR = 'Error in AES'
#
#KEYS = [
#    "FFFFFFFFFFFF",
#    "1234567890AB",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "432413243124",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF",
#    "FFFFFFFFFFFF"
#]
TAPD_TOKEN = 'nWFlu0gyx_7EqPuU3nbWaF7iqw3KDPeYxVzwQQ8yfXO46x0AnJZmQcXf3h-aEQN8xtk3OiutcL-Va6kQd2Lktw'
TAPD_HOSTNAME = 'pi3-curie'
API_LOC = 'http://localhost:8000/backend/tapd'
