# Generated by Django 2.0.3 on 2018-03-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tapinback.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=tapinback.models.gen_client_token, max_length=64)),
                ('hostname', models.CharField(max_length=30)),
                ('status', models.CharField(default='nothing', max_length=20)),
                ('username', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TapUser',
            fields=[
                ('token', models.CharField(default=tapinback.models.gen_token, max_length=672)),
                ('keys', models.CharField(default=tapinback.models.gen_keys, max_length=84)),
                ('pin', models.CharField(max_length=6)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
