# Generated by Django 2.0.3 on 2018-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapinback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
