# Generated by Django 2.0.3 on 2018-03-11 09:53

from django.db import migrations, models
import tapinback.models


class Migration(migrations.Migration):

    dependencies = [
        ('tapinback', '0002_auto_20180311_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default=tapinback.models.gen_client_token, max_length=64),
        ),
    ]
